update [dwh].[ET_Entity]
set name = 'Hoàng Văn Sương\'
	,[coordinates.longX] = NULL
	,[coordinates.latY] = NULL
	,altZ = NULL
	,nestleOwned = NULL
	,ownershipType = NULL
	,geoNodeId = 'SR_VN_1_4'
	,foundationYear = 2018
	,AAAEntryYear = 2018
	,relationshipDate = '2017-07-14 07:00:00.0000000'
	,nurseryOnSite = 1
	,millOnSite = 0
	,displayPermissionOK = NULL
	,[auditInfo.createdBy] = 'P001098'
	,[auditInfo.createdOn] = '2020-04-03 11:15:22.0000000'
	,[auditInfo.modifiedBy] = 'P001098'
	,[auditInfo.modifiedOn] = '2020-04-05 00:00:00.0000000'
	,[auditInfo.requestedBy] = NULL
	,[auditInfo.modifiedReasonCode] = NULL
	,[auditInfo.channel] = 'WEB'
	,[addressInfo.address1] = NULL
	,[addressInfo.address2] = NULL
	,[addressInfo.city] = 'Cu Kuin'
	,[addressInfo.district] = 'Cu E Wi'
	,[addressInfo.province] = 'Dak Lak'
	,[addressInfo.zipcode] = NULL
	,[addressInfo.countryCode] = NULL
	,locationVerified = NULL
	,geoStatus = NULL
	,inactivatedOn = NULL
	,AAAEnrolmentDate = NULL
	,AAAStatus = NULL
	,[4CStatus] = NULL
	,openQuantity = NULL
	,registrationNo = NULL
	,managingEntity = NULL
	,mainActivity = NULL
	,verificationType = NULL
	,completionDate = NULL
	,isPartOfAgripreneurship = NULL
	,subEntityType = 'External'
	where entityId = 'D295875E97180CD7E10000000A4E71D5';

update [dwh].[ET_Entity]
set name = 'Nông Văn Nem\'
	,[coordinates.longX] = NULL
	,[coordinates.latY] = NULL
	,altZ = NULL
	,nestleOwned = NULL
	,ownershipType = NULL
	,geoNodeId = 'SR_VN_1_4'
	,foundationYear = 2018
	,AAAEntryYear = 2018
	,relationshipDate = '2017-07-14 07:00:00.0000000'
	,nurseryOnSite = 1
	,millOnSite = 0
	,displayPermissionOK = NULL
	,[auditInfo.createdBy] = 'P001098'
	,[auditInfo.createdOn] = '2020-04-03 11:15:22.0000000'
	,[auditInfo.modifiedBy] = 'P001098'
	,[auditInfo.modifiedOn] = '2020-04-05 00:00:00.0000000'
	,[auditInfo.requestedBy] = NULL
	,[auditInfo.modifiedReasonCode] = NULL
	,[auditInfo.channel] = 'WEB'
	,[addressInfo.address1] = NULL
	,[addressInfo.address2] = NULL
	,[addressInfo.city] = 'Cu Kuin'
	,[addressInfo.district] = 'Cu E Wi'
	,[addressInfo.province] = 'Dak Lak'
	,[addressInfo.zipcode] = NULL
	,[addressInfo.countryCode] = NULL
	,locationVerified = NULL
	,geoStatus = NULL
	,inactivatedOn = NULL
	,AAAEnrolmentDate = NULL
	,AAAStatus = NULL
	,[4CStatus] = NULL
	,openQuantity = NULL
	,registrationNo = NULL
	,managingEntity = NULL
	,mainActivity = NULL
	,verificationType = NULL
	,completionDate = NULL
	,isPartOfAgripreneurship = NULL
	,subEntityType = 'External'
	where entityId = 'E095875E97180CD7E10000000A4E71D5';

select * from [dwh].[ET_Entity] where entityId = 'D295875E97180CD7E10000000A4E71D5'

