CREATE COLUMN TABLE "FARMS"."nestle.dev.glb.farms.data.structure::ET.Person"(
	"personId" VARCHAR(50) NOT NULL,
	"externalSystemId" VARCHAR(50),
	"externalSystemId2" VARCHAR(50),
	"status" NVARCHAR(50),
	"yearOfBirth" INTEGER CS_INT,
	"personInfo.firstName" NVARCHAR(255),
	"personInfo.lastName" NVARCHAR(255),
	"personInfo.dateOfBirth" SECONDDATE CS_SECONDDATE,
	"personInfo.gender" NVARCHAR(50),
	"personInfo.maritalStatus" NVARCHAR(50),
	"contactInfo.email" NVARCHAR(100),
	"contactInfo.mobilePhone" NVARCHAR(50),
	"contactInfo.fixedPhone" NVARCHAR(50),
	"entityId" VARCHAR(50) NOT NULL,
	"primaryIndicator" TINYINT CS_INT,
	"comment" NVARCHAR(5000),
	"yearStartedFarming" INTEGER CS_INT,
	"educationLevel" NVARCHAR(50),
	"yearsOfSchooling" INTEGER CS_INT,
	"worksWithCoffee" NVARCHAR(50),
	"relationToEntity" NVARCHAR(50),
	"livesAt" NVARCHAR(50),
	"deliversCoffee" NVARCHAR(50),
	"pictureId" VARCHAR(50),
	"auditInfo.createdBy" VARCHAR(50),
	"auditInfo.createdOn" LONGDATE CS_LONGDATE,
	"auditInfo.modifiedBy" VARCHAR(50),
	"auditInfo.modifiedOn" LONGDATE CS_LONGDATE,
	"auditInfo.requestedBy" VARCHAR(50),
	"auditInfo.modifiedReasonCode" NVARCHAR(50),
	"auditInfo.channel" NVARCHAR(50),
	"addressInfo.address1" NVARCHAR(255),
	"addressInfo.address2" NVARCHAR(255),
	"addressInfo.city" NVARCHAR(255),
	"addressInfo.district" NVARCHAR(255),
	"addressInfo.province" NVARCHAR(255),
	"addressInfo.zipcode" NVARCHAR(255),
	"addressInfo.countryCode" NVARCHAR(50),
	PRIMARY KEY (
		"personId"
	)
) UNLOAD PRIORITY 5 AUTO MERGE;